name: ${name}
version: ${version}
description: ${description}
author: ${author}
website: ${url}
api-version: 1.18

main: ${mainClass}

commands:
   news:
      description: Manage news items.
      usage: news

permissions:
  news:
    description: Allows users to add/remove news.
    default: op
